markdown: MacDown
theme: jekyll-theme-slate
title: Simplepayment Solutions
description: This an API documents for simplepayment solutions, the simplest payment gateway in Indonesia.
repository_url: https://github.com/simplepayment/simplepayment
